name: Create Initial Cocogitto Release
on:
  - workflow_dispatch
jobs:
  release:
    if: ${{ github.event.repository.name != 'terraform-template' }} || ${{ github.event.label.name == 'template_sync' }} # Do not run IF it is the template repo
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Check for conventional commit
        uses: cocogitto/cocogitto-action@v3.8
        with:
          check-latest-tag-only: true
      - name: Get Next Version
        id: next_version
        run: |
          echo NEXT_VERSION=$(cog bump --dry-run --auto) >> "$GITHUB_ENV"
      - name: Cocogitto release
        id: release
        uses: cocogitto/cocogitto-action@v3.8
        with:
          check-latest-tag-only: true
          release: true
      - name: Generate Changelog
        continue-on-error: true
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md
      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
