name: Remove repo from the Infracost App
on:
  - workflow_dispatch
  - delete
jobs:
  check_repository:
    runs-on: ubuntu-latest
    env:
      REPO_ID: ${{ github.event.repository.id }}
      APP_ID: ${{ secrets.INFRACOST_APP_ID }}
    steps:
      - name: Remove repo from Infracost App
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/user/installations/${{ env.APP_ID }}/repositories/${{ env.REPO_ID }}

    