name: Remove repo from the Infracost App
on:
  - workflow_dispatch
  - delete
jobs:
  check_repository:
    runs-on: ubuntu-latest
    env:
      REPO_ID: ${{ github.event.repository.id }}
      APP_ID: ${{ secrets.INFRACOST_APP_ID }}
    steps:
      - name: Enable debug logging
        run: |
            echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
            echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
      - name: "Fix initial commit message"
        uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "fix: Initial Commit"
          commit_options: "--amend"
          push_options: "--force"
          tagging_message: 'v0.0.0'
          skip_fetch: true
      - name: List org repos
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/users/Domo82/repos
      - name: Remove repo from Infracost App
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/user/installations/${{ env.APP_ID }}/repositories/${{ env.REPO_ID }}

    
