name: Remove repo from the Infracost App
on: [ delete, workflow_dispatch]
jobs:
  check_repo_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repository
        id: check_repo
        run: |
          repo_name=${{ github.event.inputs.repo_name }}
          response=$(curl -s -o /dev/null -w "%{http_code}" https://github.com/$repo_name)
          if [[ $response == "200" ]]; then
            echo "Repository $repo_name exists."
          else
            echo "Repository $repo_name does not exist."
            exit 1
          fi
                
  remove_repo:
    needs: check_repo_existence
    runs-on: ubuntu-latest
    steps:
      - name: Remove repo from Infracost app
        run: |
          curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPO_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/user/installations/${{ secrets.INFRACOST_APP_ID }}/repositories/${{ github.event.repository.id }}
    
    
