name: Remove repo from the Infracost App
on: [ delete, workflow_dispatch]
jobs:
  remove_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Remove repo from Infracost app
        run: |
          curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPO_PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/user/installations/${{ secrets.INFRACOST_APP_ID }}/repositories/${{ github.event.repository.id }}
    
    
