name: "Create Repo"

# This workflow only runs when the "Use this template" button is clicked
# As the initial github commit message placed when creating a repo from
# a template we need to ammend the commit message to comply with conventional commits

on:
  - create
  - workflow_dispatch

jobs:
  create:
    if: ${{ !github.event.repository.is_template }}
    permissions: "write-all"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
      - name: "remove this action"
        run: |
          rm -f "./.github/workflows/repo_init.yml"
      - name: Add repo to Infracost App
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/user/installations/${{ secrets.INFRACOST_APP_ID }}/repositories/${{ github.event.repository.id }}
      - name: "Fix initial commit message"
        uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "fix: Initial Commit"
          commit_options: "--amend"
          push_options: "--force"
          tagging_message: 'v0.0.0'
          skip_fetch: true
  release:
    needs: create
    if: ${{ github.event.repository.name != 'terraform-template' }} || ${{ github.event.label.name == 'template_sync' }} # Do not run IF it is the template repo
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: sleep
        run: sleep 30
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Check for conventional commit
        uses: cocogitto/cocogitto-action@v3.8
        with:
          check-latest-tag-only: true
  
      - name: Get Next Version
        id: next_version
        run: |
          echo NEXT_VERSION=`cog bump --auto --dry-run` >> "$GITHUB_ENV"

      - name: Cocogitto release
        id: release
        uses: cocogitto/cocogitto-action@v3.8
        with:
          check-latest-tag-only: true
          release: true

      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
