name: "Create Repo"

# This workflow only runs when the "Use this template" button is clicked
# As the initial github commit message placed when creating a repo from
# a template we need to ammend the commit message to comply with conventional commits

on:
  - push
  - workflow_dispatch

jobs:
  create:
    if: ${{ !github.event.repository.is_template }}
    permissions: "write-all"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: Set up cache for cog binary
        id: cache
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/cog
          key: ${{ runner.os }}-cog-${{ hashFiles('**/bin/cog') }}
          restore-keys: |
              ${{ runner.os }}-cog
      
      - name: Set up JQ
        run: sudo apt-get install jq
        
      - name: Download and install Cocogitto from the latest commit
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            REPO="cocogitto/cocogitto"
            LATEST_COMMIT_SHA=$(curl -s https://api.github.com/repos/$REPO/commits | jq -r '.[0].sha')
            curl -L "https://github.com/$REPO/archive/$LATEST_COMMIT_SHA.zip" -o cocogitto.zip
            unzip cocogitto.zip
            cd "cocogitto-$LATEST_COMMIT_SHA"
            cargo build --release
            sudo mv target/release/cog /usr/local/bin/
            cd ..
            rm -rf "cocogitto-$LATEST_COMMIT_SHA" cocogitto.zip
            
      - name: "remove this action"
        run: |
          rm -f "./.github/workflows/repo_init.yml"
          
      - name: Add repo to Infracost App
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/user/installations/${{ secrets.INFRACOST_APP_ID }}/repositories/${{ github.event.repository.id }}
            
      - name: "Fix initial commit message"
        uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "chore: Initial Commit"
          commit_options: "--amend"
          push_options: "--force"
          tagging_message: 'v0.0.0'
          skip_fetch: true
          
      - name: Get Next Version
        id: var
        run: |
          echo next_version=`git commit --allow-empty -m "fix: Initial Release Commit"` >> "$GITHUB_OUTPUT"
          
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
    
      - name: Create a GitHub release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.var.outputs.next_version }}
          name: Release ${{ steps.var.outputs.next_version }}
          body: ${{ steps.git-cliff.outputs.content }}  
